In [1]:
import numpy as np
import pandas as pd

In [2]:
# DataFrame = Таблица колонки / строки
# Series = колонка
df = pd.read_csv('../ni/data/les3_data_example.csv')
df

col1  col2  col3  col4
0       52    30     1     2
1       36    19     1     1
2       56    30     4     2
3       74    40     1     3
4       42    19     1     2
...    ...   ...   ...   ...
6157    49    29     1     2
6158    35    14     1     1
6159    29    27     1     1
6160    38    21     1     1
6161    61    31     1     2

[6162 rows x 4 columns]

In [3]:
df.head()

col1  col2  col3  col4
0    52    30     1     2
1    36    19     1     1
2    56    30     4     2
3    74    40     1     3
4    42    19     1     2

In [4]:
df.tail()

col1  col2  col3  col4
6157    49    29     1     2
6158    35    14     1     1
6159    29    27     1     1
6160    38    21     1     1
6161    61    31     1     2

In [5]:
df.describe()

col1         col2         col3         col4
count  6162.000000  6162.000000  6162.000000  6162.000000
mean     53.029049    34.603376     1.911879     1.932652
std      21.170242    19.265622     1.515550     0.815673
min       1.000000     1.000000     1.000000     1.000000
25%      38.000000    20.000000     1.000000     1.000000
50%      48.000000    30.000000     1.000000     2.000000
75%      62.000000    43.000000     2.000000     3.000000
max     637.000000   637.000000     6.000000     4.000000

In [7]:
x = df['col1'].values
x

array([52, 36, 56, ..., 29, 38, 61], dtype=int64)

In [9]:
dict_ = {
    'a' : [23, 12, 23],
    'qwerty' : [12345, 12, 32],
    'phi' : [3.14, 23, 123], 
    'values smth': [120, 324, 3],
}

df1 = pd.DataFrame(dict_)
df1

a  qwerty     phi  values smth
0  23   12345    3.14          120
1  12      12   23.00          324
2  23      32  123.00            3

In [10]:
df1.describe()

a        qwerty         phi  values smth
count   3.000000      3.000000    3.000000      3.00000
mean   19.333333   4129.666667   49.713333    149.00000
std     6.350853   7114.694395   64.240225    162.45307
min    12.000000     12.000000    3.140000      3.00000
25%    17.500000     22.000000   13.070000     61.50000
50%    23.000000     32.000000   23.000000    120.00000
75%    23.000000   6188.500000   73.000000    222.00000
max    23.000000  12345.000000  123.000000    324.00000

In [12]:
df1['a'].std()

6.3508529610858835

In [13]:
df1['a'].std(ddof=1)

6.3508529610858835

In [14]:
df1['a'].values.std()

5.185449728701348

In [15]:
df1['a'].values.std(ddof=1)

6.3508529610858835

In [11]:
df1.to_csv('les3-1.csv', index=None)

# Оценка отношений R

In [16]:
from scipy import stats

In [21]:
N = 1000
n = len(fsize)
f = n / N
N, n, f

(1000, 50, 0.05)

In [20]:
fsize = stats.poisson.rvs(2, size=50) + 1
fsize

array([3, 4, 3, 2, 2, 4, 2, 2, 2, 3, 2, 2, 3, 3, 4, 3, 3, 4, 5, 1, 1, 2,
       4, 2, 3, 2, 3, 2, 4, 3, 2, 1, 4, 4, 7, 5, 3, 3, 1, 4, 5, 2, 1, 2,
       1, 1, 4, 1, 2, 1])

In [22]:
def get_earnings(fs):
    s = stats.norm.rvs(800, 100)
    if fs > 1:
        s += stats.norm.rvs(800, 100)
    s += stats.norm.rvs(100, 20, size=max(0, fs - 2)).sum()
    return s

In [73]:
earnings = np.array([get_earnings(i) for i in fsize])
earnings

array([1569.83604562, 2004.39082573, 1886.84381798, 1778.66513437,
       1581.34685762, 1639.97171667, 1729.54036484, 1639.00280261,
       1580.55400642, 1739.95424866, 1148.05424428, 1527.22377169,
       1771.77004573, 1930.5651068 , 1836.19114936, 1637.74303801,
       1843.82797246, 1807.65130029, 2006.07881023,  930.64096693,
        897.93153374, 1504.23681021, 1950.72674312, 1599.29275512,
       1914.00000782, 1807.21418246, 1552.61988492, 1713.04715552,
       1809.22927496, 1756.19246043, 1628.21542082,  934.17063456,
       2176.77236971, 1889.60747102, 2318.820289  , 1940.76143359,
       1835.17864015, 1813.36879585,  659.29789401, 1917.5196595 ,
       1891.3897967 , 1931.37471311,  715.89792587, 1821.70814217,
        709.61777619,  717.84401895, 1841.02941463,  689.75270933,
       1406.25031578,  711.62084957])

In [74]:
fsize_mean = fsize.mean()
fsize_std = fsize.std(ddof=1)
fsize_mean, fsize_std

(2.74, 1.3218725123004527)

In [75]:
earnings_mean = earnings.mean()
earnings_std = earnings.std(ddof=1)
earnings_mean, earnings_std

(1592.8908261022382, 432.76853874933875)

In [76]:
# Доходы на одного члена семьи
# R = y.sum() / x.sum() = y.mean() / x.mean()
R = earnings_mean / fsize_mean
R

581.3470168256343

In [83]:
sR = np.sqrt(((earnings - R * fsize) ** 2).sum() / (n - 1)) * (np.sqrt(1 - f) / (np.sqrt(n) * fsize_mean))
sR

25.202805675983985

In [84]:
alpha = 0.1
left_q = stats.norm.ppf(alpha / 2)
right_q = stats.norm.ppf(1 - alpha / 2)
left_q, right_q

(-1.6448536269514729, 1.6448536269514722)

In [85]:
# CI
R + left_q * sR, R + right_q * sR

(539.8920905001389, 622.8019431511298)

# Proportions

In [93]:
a = len(fsize[fsize > 2])
a

26

In [92]:
(fsize > 2).sum()

26

In [94]:
p = a / n
p

0.52

In [95]:
A = p * N
A

520.0

In [96]:
q = 1 - p
p, q

(0.52, 0.48)

In [97]:
s2 = n * p * q / (n - 1)
s2

0.2546938775510204

In [ ]:
# CI для P

In [98]:
alpha = 0.05
lq, rq = stats.norm.ppf(alpha / 2), stats.norm.ppf(1 - alpha / 2)
lq, rq

(-1.9599639845400545, 1.959963984540054)

In [99]:
sp = np.sqrt(1 - f) * np.sqrt(p * q / (n - 1))
sp

0.06956424134186605

In [100]:
p + lq * sp - 1 / (2 * n), p + rq * sp + 1 / (2 * n)

(0.37365659235809023, 0.6663434076419098)

In [101]:
def get_spendings(fs):
    s = stats.norm.rvs(200, 25)
    if fs > 1:
        s += stats.norm.rvs(200, 25)
    s += stats.norm.rvs(160, 20, size=max(0, fs - 2)).sum()
    return s

In [104]:
spendings = [get_spendings(i) for i in fsize]
spendings

[548.1194573782005,
 703.3182470502948,
 544.7560359875824,
 402.43327053654184,
 332.94695383408157,
 651.2815431924128,
 379.6827683460875,
 405.1667637154184,
 436.3146513993471,
 608.5743392794998,
 400.13100660577254,
 431.6318019543961,
 499.41896242137614,
 517.750599426586,
 694.889953053394,
 591.3783028364255,
 572.5308168585195,
 737.7377133046473,
 925.4363661515217,
 228.20964343933989,
 193.56435126674276,
 422.3778457429668,
 769.946887236684,
 385.6069586308448,
 641.5636711585105,
 359.49412472387087,
 515.4368472250071,
 373.44302064891133,
 743.5485177383109,
 543.6685362732426,
 438.81609818035395,
 215.36438487723652,
 646.8786492792271,
 796.9190290514557,
 1264.4370192072888,
 909.0886029614358,
 557.2515446819116,
 507.71426764746036,
 194.10033325487663,
 751.7820259943409,
 841.5080675637184,
 441.29012278227367,
 172.42833464086715,
 390.5512814263009,
 188.77608073090505,
 209.64205772664616,
 738.7319725155941,
 195.67005309960172,
 426.78475432529115,
 190

In [112]:
pd.DataFrame(np.vstack([earnings, spendings]).T, columns=['earn', 'spend']).to_csv('ea_sp.csv', index=None)